services:
  - type: web
    name: jaagr
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: true
      - key: JWT_SECRET
        sync: true
      - key: JWT_EXPIRES_IN
        sync: true
      - key: PORT
        sync: true
    autoDeploy: true
